### ISSUE TITLE
Evaluation Metric

### ISSUE THREAD

**Issue by silent357** [rdroste/unisal#5]
Hi, thank you for sharing your excellent work. I have a question when I run the code. I found that the evaluation value is calculated by the average over all the videos instead of all the frames of all the videos. This makes the evaluation value higher than that calculated by the metrics used in other papers. Is my understanding right?

**Comment by rdroste** [comment]
Thanks for the question. We ensure that our evaluation is equivalent to prior work by computing the average over all videos *weighted by the respective number of frames*. This results in the same scores as computing the average over all frames of all videos. See this line in the code: https://github.com/rdroste/unisal/blob/46661a6a617c5252592c9fa51a09af482dfeac70/unisal/train.py#L776. So our implementation of the metrics produces the same results as the implementations of other papers. Let me know if you have any further questions.

**Comment by silent357** [comment]
Got it, thank you.
